# image: gitpod/workspace-full
#
image: clamer/gitpod-kubectl:1.0.0
checkoutLocation: gitpod-k8s
tasks:
  - name: dev environment
    init: |
      alias k=kubectl
      complete -F __start_kubectl k

    # command: |
    #   .my-script.sh
