# image: gitpod/workspace-full
#
image: clamer/gitpod-kubectl:1.2.3
checkoutLocation: gitpod-k8s
tasks:
  - name: dev environment
    init: |
      alias k=kubectl
      complete -F __start_kubectl k
      mkdir workshop
      clear

    # command: |
    #   .my-script.sh
